### ISSUE TITLE
update URLs to point at microsoft/cortana

### ISSUE THREAD

**Issue by mreinstein** [mreinstein/cortana-verifier#1]
@navzam did you get my invite to this project? It should be in your email.

**Comment by mreinstein** [comment]
@navzam I've copied over the initial code (which includes your recent PRs.) I reset the version number back to `0.0.1`, rebranded everything with Microsoft/Cortana, and wired up the automated tests. I'll leave it to you to take it from here and submit whatever changes you need to make so this actually works on cortana.

Once you've got a working module we can publish it to npm.

**Comment by navzam** [comment]
@mreinstein Great, and yes I got the invite, thanks!

**Comment by mreinstein** [comment]
by the way, do you have an account on npm? Happy to grant you publish access on there too.

**Comment by navzam** [comment]
@mreinstein I do now. Username is navzam

**Comment by mreinstein** [comment]
alright, you've got publish permissions on the npm module. have fun!
